# Generated by Django 4.1.3 on 2022-11-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_admin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBasedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('time', models.TimeField()),
                ('ongoing', models.BooleanField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('students', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=10000)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('homeNumber', models.CharField(max_length=20)),
                ('workNumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('sibling', models.BooleanField(default=False)),
                ('sibling_name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.parentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=10000)),
                ('availabilities', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=10000)),
                ('postalCode', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=1000)),
                ('socialSecurityNumber', models.CharField(max_length=11)),
                ('accountNumber', models.CharField(max_length=20)),
                ('routingNumber', models.CharField(max_length=20)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Payment'), (2, 'Charge'), (3, 'Discount'), (4, 'Refund')])),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('repeat', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.parentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TokenBasedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField()),
                ('ongoing', models.BooleanField()),
                ('duration', models.CharField(max_length=297)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.studentinfo')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.tutorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('date_based_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.datebasedclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.IntegerField(choices=[(1, 'Condensed'), (2, 'Normal'), (3, 'Expanded')])),
                ('include', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('footer_note', models.CharField(blank=True, max_length=1000)),
                ('private_note', models.CharField(blank=True, max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.parentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='datebasedclass',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.tutorinfo'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('feedback', models.TextField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_based_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.datebasedclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.studentinfo')),
            ],
        ),
    ]
