# Generated by Django 4.1.3 on 2023-04-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='additional_info',
            field=models.TextField(default='good'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='country',
            field=models.CharField(default='Texas', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='state',
            field=models.CharField(default='New York', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='zip_code',
            field=models.CharField(default='12345', max_length=10000),
            preserve_default=False,
        ),
    ]
