# Generated by Django 4.1.3 on 2023-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0002_remove_parentinfo_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='add_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='state',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
