# Generated by Django 4.1.3 on 2023-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0004_remove_studentinfo_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='branch',
        ),
    ]
