# Generated by Django 4.1.3 on 2023-05-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0005_remove_studentinfo_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='isAdult',
            field=models.BooleanField(default=False),
        ),
    ]
