# Generated by Django 4.1.3 on 2023-05-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0006_studentinfo_isadult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='homeNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='workNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
