# Generated by Django 4.1.3 on 2023-05-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0008_rename_tutorinfo_employeeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='DateTime',
            new_name='hireDate',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='availabilities',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='availableDays',
            field=models.CharField(default='days', max_length=500),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='country',
            field=models.CharField(default='USA', max_length=1000),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='endingTime',
            field=models.TimeField(default=datetime.datetime(2023, 5, 13, 18, 28, 23, 252843, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='startingTime',
            field=models.TimeField(default=datetime.datetime(2023, 5, 13, 18, 28, 37, 767246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='state',
            field=models.CharField(default='USA', max_length=1000),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='add_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='address',
            field=models.CharField(default='USA', max_length=10000),
        ),
    ]
