# Generated by Django 4.1.3 on 2023-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0009_rename_datetime_employeeinfo_hiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='endingTime',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='startingTime',
            field=models.CharField(max_length=2000),
        ),
    ]
