# Generated by Django 4.1.3 on 2023-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0010_alter_employeeinfo_endingtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='availableDays',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='endingTime',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='startingTime',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='availablilityData',
            field=models.CharField(default='days', max_length=500),
            preserve_default=False,
        ),
    ]
