# Generated by Django 4.1.3 on 2023-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0011_remove_employeeinfo_availabledays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='availablilityData',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='maritalStatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
