# Generated by Django 4.1.3 on 2023-05-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0012_alter_employeeinfo_availablilitydata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='bio',
            new_name='add_info',
        ),
    ]
