# Generated by Django 4.1.3 on 2023-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0014_studentinfo_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='subjects',
            field=models.CharField(default='["math","chemistry","physics"]', max_length=10000),
            preserve_default=False,
        ),
    ]
