# Generated by Django 4.1.3 on 2023-06-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0015_studentinfo_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinfo',
            name='isAdult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='add_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
