# Generated by Django 4.1.3 on 2023-06-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0002_remove_branchinfo_branchadminemail_branchinfo_city_and_more'),
        ('branch_admin', '0016_parentinfo_isadult_alter_studentinfo_add_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('modules', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='datebasedclass',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='datebasedclass',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='date_based_class',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tokenbasedclass',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tokenbasedclass',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tokenbasedclass',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='DateBasedClass',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='TokenBasedClass',
        ),
    ]
