# Generated by Django 4.1.3 on 2023-06-23 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0002_remove_branchinfo_branchadminemail_branchinfo_city_and_more'),
        ('branch_admin', '0017_classmodel_remove_datebasedclass_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.IntegerField(choices=[(1, 'group'), (2, 'private')])),
                ('description', models.TextField(blank=True)),
                ('availablilityData', models.CharField(max_length=5000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo')),
                ('students', models.ManyToManyField(to='branch_admin.studentinfo')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.employeeinfo')),
            ],
        ),
    ]
