# Generated by Django 4.1.3 on 2023-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0018_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
