# Generated by Django 4.1.3 on 2023-07-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0020_classschedule_endingdate_classschedule_startingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='referenceClass',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='branch_admin.classmodel'),
            preserve_default=False,
        ),
    ]
