# Generated by Django 4.1.3 on 2023-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0023_invoice_delete_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceType',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='class_schedule',
        ),
        migrations.AddField(
            model_name='invoice',
            name='class_schedule',
            field=models.ManyToManyField(to='branch_admin.classschedule'),
        ),
    ]
