# Generated by Django 4.1.3 on 2023-10-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0024_remove_invoice_invoicetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='branch',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Enter the price of the service in US dollars.', max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch_admin.invoice'),
        ),
    ]
