# Generated by Django 4.1.3 on 2023-10-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0025_remove_transactions_branch_classschedule_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='family',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
