# Generated by Django 4.1.3 on 2023-10-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0026_remove_invoice_family_remove_invoice_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parent',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='branch_admin.parentinfo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='students',
            field=models.ManyToManyField(to='branch_admin.classschedule'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='class_schedule',
            field=models.ManyToManyField(related_name='class_schedule', to='branch_admin.classschedule'),
        ),
    ]
