# Generated by Django 4.1.3 on 2023-10-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0027_invoice_parent_invoice_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='students',
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='branch_admin.classschedule'),
            preserve_default=False,
        ),
    ]
