# Generated by Django 4.1.3 on 2023-10-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0028_remove_invoice_parent_remove_invoice_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='class_schedule',
            new_name='class_schedules',
        ),
    ]
