# Generated by Django 4.1.3 on 2023-10-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0029_rename_class_schedule_invoice_class_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_admin.studentinfo'),
        ),
    ]
