# Generated by Django 4.1.3 on 2023-10-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0002_remove_branchinfo_branchadminemail_branchinfo_city_and_more'),
        ('branch_admin', '0030_alter_invoice_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchinfo'),
            preserve_default=False,
        ),
    ]
