# Generated by Django 4.1.3 on 2023-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_admin', '0031_invoice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
