# Generated by Django 4.1.3 on 2023-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_rename_user_otpmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
