# Generated by Django 4.1.3 on 2023-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_otpmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
