# Generated by Django 4.1.3 on 2022-11-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10000)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=1000)),
                ('locationAddress', models.CharField(max_length=10000)),
                ('branchAdminEmail', models.EmailField(max_length=254)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('branchAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.branchadmininfo')),
            ],
        ),
    ]
